version: 0.0.1.{build}
platform: x64
image: Visual Studio 2017

init:
  - git config --global core.autocrlf true

install:
  - go version
  - go env

build_script:
  - compile.cmd

test: off

artifacts:
  - path: bin
    name: bin

