version: 0.0.1.{build}
platform: x64
image: Visual Studio 2017

init:
  - git config --global core.autocrlf true

install:
  - rmdir c:\go /s /q
  - appveyor DownloadFile https://dl.google.com/go/go1.12.1.windows-amd64.msi
  - msiexec /i go1.12.1.windows-amd64.msi /q
  - go version
  - go env

build_script:
  - compile.cmd

test_script:
  - run_tests.cmd

artifacts:
  - path: bin
    name: bin

